CREATE TABLE IF NOT EXISTS transactions (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  client_id INT UNSIGNED NOT NULL,
  currency_id INT UNSIGNED NOT NULL,
  chain VARCHAR(255) DEFAULT NULL,
  type VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL,
  txid VARCHAR(255) NOT NULL,
  vout INT UNSIGNED DEFAULT NULL,
  amount BIGINT(20) UNSIGNED NOT NULL,
  address_from VARCHAR(255) DEFAULT NULL,
  address_to VARCHAR(255) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (client_id) REFERENCES clients(id),
  FOREIGN KEY (currency_id) REFERENCES currencies(id),
  UNIQUE (chain, txid)
);